version: '3.8'

services:
  streamlit-app:
    container_name: steamlit-interactive-ml-dashboard
    image : amritpalbasi/steamlit-interactive-ml-dashboard
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - STREAMLIT_SERVER_PORT=8501
    command: streamlit run app/main.py
